# Generated by Django 5.0.2 on 2024-02-08 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnesKurtTest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Geo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=20)),
                ('lng', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='album',
            old_name='user',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='post',
            new_name='postid',
        ),
        migrations.RenameField(
            model_name='photos',
            old_name='album',
            new_name='albumId',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='user',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='todos',
            old_name='user',
            new_name='userId',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='website',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EnesKurtTest.address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EnesKurtTest.company'),
        ),
        migrations.AddField(
            model_name='address',
            name='geo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EnesKurtTest.geo'),
        ),
    ]
