# Generated by Django 5.0.2 on 2024-02-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnesKurtTest', '0002_address_company_geo_rename_user_album_userid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.JSONField(),
        ),
    ]
