# Generated by Django 5.0.2 on 2024-02-08 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnesKurtTest', '0003_alter_user_address_alter_user_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='geo',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Geo',
        ),
    ]
